# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/


screenshots_path "fastlane/screenshots/framed/en-US"

skip_binary_upload true

# overwrite_screenshots true
