# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/


screenshots_path "fastlane/screenshots/framed"

skip_binary_upload true
app_version("1.9.0")

# overwrite_screenshots true
