# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    xcodes(
      select_for_current_build_only: true
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_KEY_FILEPATH"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      in_house: false,
    )

    sync_code_signing(
      type: "appstore",
      app_identifier: [
        "com.paulgessinger.swift-paperless",
        "com.paulgessinger.swift-paperless.ShareExtension"
    ])

    ensure_git_branch(branch: "^main|develop\/.+$")
    ensure_git_status_clean
    git_pull(rebase: true)

    previous_build_number = latest_testflight_build_number()
    current_build_number = previous_build_number + 1

    last_tag = last_git_tag()

    changelog = sh("git cliff --config fastlane/cliff.toml -w .. --unreleased 2> /dev/null")

    increment_build_number(
      xcodeproj: "swift-paperless.xcodeproj",
      build_number: current_build_number
    )

    build_app(scheme: "swift-paperless")

    git_commit(
      path: "swift-paperless.xcodeproj",
      message: "Bump build number to #{current_build_number}"
    )

    add_git_tag(prefix: "v", includes_lane: false)

    upload_to_testflight(changelog: changelog)

    push_to_git_remote(tags: true)
  end

  lane :bump_build do
    previous_build_number = latest_testflight_build_number()
    current_build_number = previous_build_number + 1

    increment_build_number(
      xcodeproj: "swift-paperless.xcodeproj",
      build_number: current_build_number
    )
  end

  lane :tests do
    xcodes(
      select_for_current_build_only: true
    )

    run_tests(
      scheme: "swift-paperlessTests",
      xcargs: "-skipPackagePluginValidation",
      output_types: ""
    )

    spm(
      command: "test",
      package_path: "Common",
    )
  end

  lane :build do |options|
    xcodes(
      select_for_current_build_only: true
    )

    device = options.fetch(:device, "iPhone 15 Pro")
    ios = options.fetch(:ios, "17.4")


    build_app(
      scheme: "swift-paperless",
      destination: "platform=iOS Simulator,OS=#{ios},name=#{device}",
      xcargs: "-skipPackagePluginValidation"
    )
  end

  lane :screenshots do
    xcodes(
      select_for_current_build_only: true
    )

    snapshot()
  end
end
