name: Upload existing translations to Crowdin

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-translations:
    name: Upload translations
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Upload existing translations
        uses: crowdin/github-action@9af557de76d70c480f88065d336f445a362f402b # v3.1.0
        with:
          command: push translations
