name: Documentation

on:
  push:

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Build documentation
        run: |
          uvx \
            --from 'zensical==0.0.40' \
            --with 'mkdocs-redirects==1.2.2' \
            --with 'mkdocs-literate-nav==0.6.2' \
            --with 'mkdocs-exclude==1.0.2' \
            --with 'pymdown-extensions==10.21.2' \
            zensical build
          mkdir site/release_notes/md
          cp docs/release_notes/*.md site/release_notes/md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
