name: Check upstream filter rule types

on:
  schedule:
    - cron: "7 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update_filter_rules:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      # For gh cli in generate_filterrules.py
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5
        with:
          prek-version: '0.3.x'
          install-only: true

      - name: Generate filter rules
        run: |
          uv run scripts/generate_filterrules.py --output DataModel/Sources/DataModel/FilterRuleType.swift
          prek run swift-format --files DataModel/Sources/DataModel/FilterRuleType.swift || true

      - run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: 'chore: Update Filter Rule types'
          commit-message: 'chore: Update Filter Rule types'
          branch: filter-rule-type-update
          delete-branch: true
          body: "Automated update of Filter Rule types."
          base: main
          add-paths: DataModel/Sources/DataModel/FilterRuleType.swift
